[workspace]
authors = ["YangWiz <polymagicyang@gmail.com>"]
channels = ["conda-forge"]
name = "green-lab-group1"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.2,<3"
psutil = ">=7.1.0,<8"
tabulate = ">=0.9.0,<0.10"
dill = ">=0.4.0,<0.5"
jsonpickle = ">=4.1.1,<5"
